ow2-proactive/scheduling-api

README.md, scheduling-api-graphql/scheduling-api-graphql-beans/src/main/resources/json/jobConnection.json, scheduling-api-graphql/scheduling-api-graphql-beans/src/main/resources/json/jobNode.json, scheduling-api-graphql/scheduling-api-graphql-beans/src/main/resources/json/jobs.json, scheduling-api-graphql/scheduling-api-graphql-beans/src/main/resources/json/node.json, scheduling-api-graphql/scheduling-api-graphql-beans/src/main/resources/json/taskConnection.json, scheduling-api-graphql/scheduling-api-graphql-beans/src/main/resources/json/taskNode.json, scheduling-api-graphql/scheduling-api-graphql-beans/src/main/resources/json/tasks.json, scheduling-api-graphql/scheduling-api-graphql-beans/src/test/java/org/ow2/proactive/scheduling/api/graphql/beans/SchedulingApiResponseTest.java, scheduling-api-graphql/scheduling-api-graphql-beans/src/test/resources/jobs.json, scheduling-api-graphql/scheduling-api-graphql-client/src/main/java/org/ow2/proactive/scheduling/api/graphql/client/beans/Jobs.java, scheduling-api-graphql/scheduling-api-graphql-client/src/main/java/org/ow2/proactive/scheduling/api/graphql/client/beans/Query.java, scheduling-api-graphql/scheduling-api-graphql-client/src/main/java/org/ow2/proactive/scheduling/api/graphql/client/beans/Viewer.java, scheduling-api-graphql/scheduling-api-graphql-client/src/test/java/org/ow2/proactive/scheduling/api/graphql/client/beans/JobTest.java
1. fix genericInformation deserialization bug (change the type from Map to List)
2. have a dedicated connection for job and task, so that the node type for each connection is dedicated as well. This avoid the casting exception from Node, to JobNode on client side
3. update README.md according to the latest change
=> bug fix and readme update

scheduling-api-graphql/scheduling-api-graphql-fetchers/src/main/java/org/ow2/proactive/scheduling/api/graphql/fetchers/JobDataFetcher.java, scheduling-api-graphql/scheduling-api-graphql-fetchers/src/test/java/org/ow2/proactive/scheduling/api/graphql/fetchers/JobDataFetcherTest.java
job's variables field has been changed to a map of JobVariable object instead of a map of string.
update the jobDataFetcher for this change
=> Partially map the new JobVariable object to String

scheduling-api-graphql/scheduling-api-graphql-beans/scheduling-api-graphql-beans-input/src/main/java/org/ow2/proactive/scheduling/api/graphql/beans/input/JobInput.java
Otherwise it's impossible to filter according to status
=> Job status needs to be JobStatus type and not String

scheduling-api-graphql/scheduling-api-graphql-beans/scheduling-api-graphql-beans-input/src/main/java/org/ow2/proactive/scheduling/api/graphql/beans/input/JobInput.java
Because it is an enum value and not a String)
=> Remove quotes around Priority filter to build query

scheduling-api-graphql/scheduling-api-graphql-beans/scheduling-api-graphql-beans-input/src/main/java/org/ow2/proactive/scheduling/api/graphql/beans/input/Jobs.java, scheduling-api-graphql/scheduling-api-graphql-beans/scheduling-api-graphql-beans-input/src/main/java/org/ow2/proactive/scheduling/api/graphql/beans/input/ResultMap.java, scheduling-api-graphql/scheduling-api-graphql-beans/scheduling-api-graphql-beans-output/src/main/resources/json/node.json, scheduling-api-graphql/scheduling-api-graphql-client/src/test/java/org/ow2/proactive/scheduling/api/graphql/client/beans/JobTest.java, scheduling-api-graphql/scheduling-api-graphql-client/src/test/java/org/ow2/proactive/scheduling/api/graphql/client/beans/KeyValueTest.java, scheduling-api-graphql/scheduling-api-graphql-client/src/test/java/org/ow2/proactive/scheduling/api/graphql/client/beans/ViewerTest.java, scheduling-api-graphql/scheduling-api-graphql-common/src/main/java/org/ow2/proactive/scheduling/api/graphql/common/Fields.java, scheduling-api-graphql/scheduling-api-graphql-fetchers/src/main/java/org/ow2/proactive/scheduling/api/graphql/fetchers/JobDataFetcher.java, scheduling-api-graphql/scheduling-api-graphql-fetchers/src/main/java/org/ow2/proactive/scheduling/api/graphql/fetchers/KeyValues.java, scheduling-api-graphql/scheduling-api-graphql-fetchers/src/main/java/org/ow2/proactive/scheduling/api/graphql/fetchers/ResultMapDataFetcher.java, scheduling-api-graphql/scheduling-api-graphql-schema/src/main/java/org/ow2/proactive/scheduling/api/graphql/schema/type/Job.java, scheduling-api-graphql/scheduling-api-graphql-schema/src/main/java/org/ow2/proactive/scheduling/api/graphql/schema/type/Query.java, scheduling-api-graphql/scheduling-api-graphql-schema/src/main/java/org/ow2/proactive/scheduling/api/graphql/schema/type/ResultMap.java, scheduling-api-graphql/scheduling-api-graphql-schema/src/main/java/org/ow2/proactive/scheduling/api/graphql/schema/type/User.java, scheduling-api-graphql/scheduling-api-graphql-schema/src/main/java/org/ow2/proactive/scheduling/api/graphql/schema/type/interfaces/KeyValue.java, scheduling-api-graphql/scheduling-api-graphql-services/src/main/java/org/ow2/proactive/scheduling/api/graphql/service/GraphqlService.java
In this PR, we add the ResultMap to the job properties returned by GraphQL queries about jobs
=> Add Job ResultMap to graphql query results

scheduling-api-graphql/scheduling-api-graphql-beans/scheduling-api-graphql-beans-input/src/main/java/org/ow2/proactive/scheduling/api/graphql/beans/input/JobInput.java, scheduling-api-graphql/scheduling-api-graphql-fetchers/src/main/java/org/ow2/proactive/scheduling/api/graphql/fetchers/converter/JobInputConverter.java, scheduling-api-http/src/integration-test/java/org/ow2/proactive/scheduling/api/GraphqlServiceIntegrationTest.java
- builder is used from the scheduler portal
- also fix the filtering by variable name or variable value only
=> Add JobInput variable builder

scheduling-api-graphql/scheduling-api-graphql-beans/scheduling-api-graphql-beans-input/build.gradle, scheduling-api-graphql/scheduling-api-graphql-beans/scheduling-api-graphql-beans-input/src/main/java/org/ow2/proactive/scheduling/api/graphql/beans/input/Inputs.java, scheduling-api-graphql/scheduling-api-graphql-beans/scheduling-api-graphql-beans-input/src/main/java/org/ow2/proactive/scheduling/api/graphql/beans/input/JobInput.java, scheduling-api-graphql/scheduling-api-graphql-beans/scheduling-api-graphql-beans-input/src/main/java/org/ow2/proactive/scheduling/api/graphql/beans/input/KeyValueInput.java, scheduling-api-graphql/scheduling-api-graphql-beans/scheduling-api-graphql-beans-input/src/main/java/org/ow2/proactive/scheduling/api/graphql/beans/input/TaskInput.java
- use commons lang to escape characters when building json strings
=> Escape characters in json strings

scheduling-api-graphql/scheduling-api-graphql-client/build.gradle, scheduling-api-graphql/scheduling-api-graphql-client/src/main/java/org/ow2/proactive/scheduling/api/graphql/client/SchedulingApiClient.java
- add apache http client dependency
- disable hostname and certificate check
=> Disable certficate check on SchedulingApiClient

scheduling-api-graphql/scheduling-api-graphql-beans/scheduling-api-graphql-beans-input/src/main/java/org/ow2/proactive/scheduling/api/graphql/beans/input/JobInput.java, scheduling-api-graphql/scheduling-api-graphql-beans/scheduling-api-graphql-beans-input/src/main/java/org/ow2/proactive/scheduling/api/graphql/beans/input/TaskInput.java, scheduling-api-graphql/scheduling-api-graphql-client-gwt/src/main/java/org/ow2/proactive/scheduling/api/graphql/client/SchedulingApiClientGwt.java, scheduling-api-graphql/scheduling-api-graphql-client/src/integration-test/java/org/ow2/proactive/scheduling/api/graphql/client/SchedulingApiClientTest.java, scheduling-api-graphql/scheduling-api-graphql-common/src/main/java/org/ow2/proactive/scheduling/api/graphql/common/InputFields.java, scheduling-api-graphql/scheduling-api-graphql-fetchers/src/main/java/org/ow2/proactive/scheduling/api/graphql/fetchers/converter/JobInputConverter.java, scheduling-api-graphql/scheduling-api-graphql-fetchers/src/main/java/org/ow2/proactive/scheduling/api/graphql/fetchers/converter/TaskInputConverter.java, scheduling-api-graphql/scheduling-api-graphql-fetchers/src/test/java/org/ow2/proactive/scheduling/api/graphql/fetchers/JobDataFetcherTest.java, scheduling-api-graphql/scheduling-api-graphql-schema/src/main/java/org/ow2/proactive/scheduling/api/graphql/schema/type/inputs/JobInput.java, scheduling-api-graphql/scheduling-api-graphql-schema/src/main/java/org/ow2/proactive/scheduling/api/graphql/schema/type/inputs/JobStatusInput.java, scheduling-api-graphql/scheduling-api-graphql-schema/src/main/java/org/ow2/proactive/scheduling/api/graphql/schema/type/inputs/JobTaskCommonAbstractInput.java, scheduling-api-graphql/scheduling-api-graphql-schema/src/main/java/org/ow2/proactive/scheduling/api/graphql/schema/type/inputs/TaskInput.java, scheduling-api-graphql/scheduling-api-graphql-schema/src/main/java/org/ow2/proactive/scheduling/api/graphql/schema/type/inputs/TaskStatusInput.java
=> Implement the IN operator for the job and task statuses filtering

scheduling-api-graphql/scheduling-api-graphql-fetchers/src/main/java/org/ow2/proactive/scheduling/api/graphql/fetchers/DatabaseConnectionFetcher.java, scheduling-api-http/src/integration-test/java/org/ow2/proactive/scheduling/api/GraphqlServiceIntegrationTest.java
- hasNext and hasPrevious returned invalid result and was not taking into account the cursors (before or after). Fixed it by using the cursor in the count query.
- improved and refactored some tests
=> Fix hasNext and hasPrevious

scheduling-api-graphql/scheduling-api-graphql-fetchers/src/main/java/org/ow2/proactive/scheduling/api/graphql/fetchers/JobDataFetcher.java
Call toString on Object instead of cast
=> Fix JobDataFetcher

scheduling-api-graphql/scheduling-api-graphql-beans/scheduling-api-graphql-beans-input/src/main/java/org/ow2/proactive/scheduling/api/graphql/beans/input/JobInput.java, scheduling-api-graphql/scheduling-api-graphql-schema/src/main/java/org/ow2/proactive/scheduling/api/graphql/schema/type/inputs/JobInput.java, scheduling-api-graphql/scheduling-api-graphql-schema/src/main/java/org/ow2/proactive/scheduling/api/graphql/schema/type/inputs/StartTimeInput.java
- be coherent with startTime naming
=> Add new filters for scheduling-api

scheduling-api-http/build.gradle, scheduling-api-http/src/main/java/org/ow2/proactive/scheduling/api/Application.java
- use jasypt and jasypt-spring-boot to decrypt properties
- add required annotation
=> Add configuration passwords encryption

scheduling-api-graphql/scheduling-api-graphql-fetchers/src/main/java/org/ow2/proactive/scheduling/api/graphql/fetchers/DatabaseConnectionFetcher.java, scheduling-api-graphql/scheduling-api-graphql-fetchers/src/main/java/org/ow2/proactive/scheduling/api/graphql/fetchers/JobDataFetcher.java, scheduling-api-graphql/scheduling-api-graphql-fetchers/src/main/java/org/ow2/proactive/scheduling/api/graphql/fetchers/TaskDataFetcher.java, scheduling-api-graphql/scheduling-api-graphql-fetchers/src/main/java/org/ow2/proactive/scheduling/api/graphql/fetchers/converter/AbstractJobTaskInputConverter.java, scheduling-api-graphql/scheduling-api-graphql-fetchers/src/main/java/org/ow2/proactive/scheduling/api/graphql/fetchers/converter/JobInputConverter.java, scheduling-api-graphql/scheduling-api-graphql-fetchers/src/main/java/org/ow2/proactive/scheduling/api/graphql/fetchers/converter/TaskInputConverter.java
Adapt the variable value filter to use PostgreSQL native functions
=> Fix variable value filter query for PostgreSQL

scheduling-api-graphql/scheduling-api-graphql-fetchers/build.gradle, scheduling-api-graphql/scheduling-api-graphql-fetchers/src/main/java/org/ow2/proactive/scheduling/api/graphql/fetchers/DatabaseConnectionFetcher.java, scheduling-api-http/src/main/resources/application-test.properties, scheduling-api-http/src/main/resources/application.properties
- also, ensure database access and transactions are read-only (hint to the database)
- remove tomcat dependencies
=> Fix Hikari configuration

scheduling-api-graphql/scheduling-api-graphql-fetchers/src/main/java/org/ow2/proactive/scheduling/api/graphql/fetchers/DatabaseConnectionFetcher.java, scheduling-api-graphql/scheduling-api-graphql-fetchers/src/main/java/org/ow2/proactive/scheduling/api/graphql/fetchers/converter/JobInputConverter.java, scheduling-api-http/src/integration-test/java/org/ow2/proactive/scheduling/api/GraphqlServiceIntegrationTest.java
Additionally:
- use count instead of count(distinct) to improve performance
- improve integration test for variables filter
=> Discontinued support for removeTime

scheduling-api-graphql/scheduling-api-graphql-fetchers/build.gradle, scheduling-api-http/build.gradle, scheduling-api-http/src/main/resources/application.properties, scheduling-api-http/src/main/resources/log4j2.xml
- make sure slf4j redirects to log4j2 and not log4j
- include hikari to let the web application load it
- fix hikari properties
=> Improve log management

scheduling-api-graphql/scheduling-api-graphql-fetchers/build.gradle
This is to fix database connection issues
=> Upgrade hikari version

scheduling-api-graphql/scheduling-api-graphql-fetchers/src/main/java/org/ow2/proactive/scheduling/api/graphql/fetchers/DatabaseConnectionFetcher.java, scheduling-api-graphql/scheduling-api-graphql-fetchers/src/main/java/org/ow2/proactive/scheduling/api/graphql/fetchers/HSQLDBInterceptor.java, scheduling-api-graphql/scheduling-api-graphql-fetchers/src/main/java/org/ow2/proactive/scheduling/api/graphql/fetchers/JobDataFetcher.java, scheduling-api-graphql/scheduling-api-graphql-fetchers/src/main/java/org/ow2/proactive/scheduling/api/graphql/fetchers/TaskDataFetcher.java, scheduling-api-http/src/main/resources/application-test.properties, scheduling-api-http/src/main/resources/application.properties
This interceptor adds USING INDEX ta a sql query that contains ORBER BY and LIMIT, this is to use indexes on order by columns
=> Add HSQLDB interceptor

scheduling-api-graphql/scheduling-api-graphql-client/build.gradle
Upgrade the following dependency to the version mentioned in **bold**:
- org.apache.httpcomponents:httpclient:**4.5.14**
=> Upgrade keycloak related dependencies
